### ISSUE TITLE
How to generate bible with the text included

### ISSUE THREAD

**Issue by wsamuels1127** [GsLogiMaker/my-bible-obsidian-plugin#1]
The plugin (at least for my version of the Bible, the VFL) does not put the verses in plain text, but instead with the ``` verse ``` thing. I need it to be in true plain text because I need to send it to other people. How do I fix this?

**Comment by GsLogiMaker** [comment]
Creating plain text files that work outside Obsidian is currently not supported. I'll go ahead and add that as a feature.

**Comment by GsLogiMaker** [comment]
I've added a pre-release with the new feature.
https://github.com/GsLogiMaker/my-bible-obsidian-plugin/releases/tag/1.1.1.prerelease.1

To use it, make sure the `Build with dynamic verses` settings is `Off` and that the `Verse body format` setting uses `{verse_text}` if isn't already.

![mybible_example](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/87501052/e74abd8d-8e9a-479d-a5b3-61f89f9efa26)

Let me know if this helps. God bless!

**Comment by wsamuels1127** [comment]
EPIC THANKS
