### ISSUE TITLE
Bible Table of Contents

### ISSUE THREAD

**Issue by Red-Beard08** [GsLogiMaker/my-bible-obsidian-plugin#13]
I created a page called "Bible" and created a page listing there for each book (eg [[Genesis]], [[Exodus]], etc) then back on the chapter pages replaced the [[Matthew]] link with [[Bible|Matthew]].

This allows you to navigate to all other books easily, avoids having a potential dead page link on every chapter, and presents a very pretty picture in the graph view since all the pages tie back to the "Bible" page. 

Might be a good additional feature. 

![image](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/14928358/e92e50e0-20a3-4134-ba52-f28e3fa8de69)
![image](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/14928358/5c79af00-d565-492b-a3d1-dff4be6a8e80)

**Comment by GsLogiMaker** [comment]
Will have to add this for sure! 👍
