### ISSUE TITLE
Verse numbers wrong if there are omitted verses in text

### ISSUE THREAD

**Issue by aaldrich29** [GsLogiMaker/my-bible-obsidian-plugin#19]
Matthew 23 in ESV is the example I ran into today. Verse 14, at least in ESV, is omitted in the ESV version of the text.

But the plugin seems to not be aware that it should omit verse number 14, so verse 15 is called 14; verse 16 is called 16, etc.

**Comment by GsLogiMaker** [comment]
I'll look into it! 👍

**Comment by GsLogiMaker** [comment]
I pushed a fix that will take effect in the next update. Thanks for the report!

**Comment by aaldrich29** [comment]
Thank you!
