### ISSUE TITLE
Download translation?

### ISSUE THREAD

**Issue by billpetro** [GsLogiMaker/my-bible-obsidian-plugin#2]
I've installed the plugin as instructions directed. When I do CMD-P "My Bible: Download translation" it 
- Asks if I want to download the entire ESV translation

When I click Download it:
- Started download of the ESV translation

Then almost immediately says:
- Completed download of the ESV translation

But I see no indication of the presence of the translation in /Bible or anywhere else in my vault.

Nor does it populate a verse when I "read" it with "[[Genesis 1#1]]" instead it merely displays the location in /Bible/01 Genesis/Genesis 1

What am I missing?

**Comment by GsLogiMaker** [comment]
When you have a built Bible in your vault, the verses displayed in the bible are fetched from the internet. Downloading the Bible means you have a local copy that can be accessed without an internet connection.

You can verify if the translation has been downloaded by opening your vault in the OS's file explorer, and navigating to `.obsidian/plugins/gslogimaker-my-bible/.mybiblecache`, and you should see a lot of text files containing the text of your translation.

If you don't have the Bible built in your vault then you can run the `Build Bible` command with CMD-P "My Bible: Build bible", and that will build your Bible in the path specified in your My Bible settings.

![mybible_example1](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/87501052/fb00d339-f70e-4a51-be94-32069c037e32)

Hope this helps!

**Comment by billpetro** [comment]
Thanks. The picture you show here of the Bible folder as "Bible" with an emoticon is different than the default "/Bible/". With the default, you get the skeleton, but the `My Bible: Download translation` doesn't work.

With "Bible" it does. I now have 4BM of files in .obsidian/plugins/gslogimaker-my-bible

![LanguageTool_Underlines_Overlay](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/561093/c493a55c-95c2-46a1-8fcc-a09742ad03b9)

They look like this:

![LanguageTool_Underlines_Overlay](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/561093/af00cdf3-aff9-452e-ab31-b8520057c248)

Question: how do I get them to appear?

Typing `[[Genesis 1#1]]` , which in Reading mode, looks like `Genesis 1>1` opens `Bible/01 Genesis/Genesis 1` and gives me a highlight, but empty location here:

![LanguageTool_Underlines_Overlay](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/561093/14d00133-e5c2-42b9-a463-572a7fa97b1a)

**Comment by GsLogiMaker** [comment]
I see the issue. Looks like My Bible is using an incorrect default for one of the settings.
Change the `Verse body format` setting to 
```
###### {verse}
{verse_text}
```
and run `Build bible` again. That should fix the problem.

![mybible_example2](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/87501052/7dca902e-c2e3-4436-b7b3-360f7d56abf6)

**Comment by billpetro** [comment]
Success! Thanks.
