### ISSUE TITLE
instead of linking to bolls, could we actually download the text

### ISSUE THREAD

**Issue by captaincanuk** [GsLogiMaker/my-bible-obsidian-plugin#20]
I find that this is actually of very little use since i cannot search for text (e.g. search for the name Joseph or Canaan), and file links do not work for keywords.

I did try downloading the bible text from Bolls and was successful (ESV was 2.4 MB zipped, 10.6 MB as JSON) but it will be quite a chore to format into the chapters in your layout. BTW I really do like your layout as I can create links down to the verse level.

Thank your for your work on this,

Ian Campbell CPA, CMA, CMC
E: iscampbell@iscampbell.ca

**Comment by GsLogiMaker** [comment]
It's already possible to build your Bible with text instead of with blocks for verses. This would allow you to search your Bible with Obsidian's search features.
However, I don't know if its possible to add search functionality to the dynamic verses.

**Comment by GsLogiMaker** [comment]
Disable the `Build with dynamic verses` setting before you build your Bible and it will be built with the text of your current translation.

**Comment by captaincanuk** [comment]
This is absolutely fantastic. Thank you so much.

Ian

**Comment by GsLogiMaker** [comment]
God bless!
