### ISSUE TITLE
Most Settings Missing

### ISSUE THREAD

**Issue by aaldrich29** [GsLogiMaker/my-bible-obsidian-plugin#21]
I'm not sure if it's just me or not, but in the latest version I only have a setting for the translation, and nothing else. I even tried it in a fresh vault.

![image](https://github.com/user-attachments/assets/0097066b-5ae8-4915-a3b7-edb13c887268)

**Comment by GsLogiMaker** [comment]
I've moved the settings related to building your Bible to the new builder menu, which can be found by running the `Build Bible` command.

**Comment by GsLogiMaker** [comment]
Maybe I should add some text to the settings menu explaining the move so that people don't get confused.

**Comment by GsLogiMaker** [comment]
I pushed a patch explaining the moved settings. I'll close this issue now.
