### ISSUE TITLE
My Bible

### ISSUE THREAD

**Issue by Pjhers** [GsLogiMaker/my-bible-obsidian-plugin#28]
when creating multiple links and open any of the links, the chapter but does not indicator the verse number. can you assist pleaseWhen creating multiple links and opening any of them, the chapter is displayed but does not indicate the verse number. Can you assist, please?

**Comment by GsLogiMaker** [comment]
I'll help! What were you trying to do? Could you provide a screenshot of what is happening and describe what you expected?
