### ISSUE TITLE
Is there a bug resulting in a mismatch between search code and verse?

### ISSUE THREAD

**Issue by JSJ10FL** [GsLogiMaker/my-bible-obsidian-plugin#29]
Hello
I am enjoying the plug in
But for some reason when I call for John 13.34-35 for example, I have to use this code to get the right verse. 

```verse
43 13 35-36
```
Is there an extra verse lurking earlier in the text that is causing trouble? I haven't been right through to find it. 
Hope this is helpful.

**Comment by GsLogiMaker** [comment]
Yes, there is. I'll get that fixed!

**Comment by GsLogiMaker** [comment]
Also, if it helps, you can also write the codeblock like this:
```verse
John 13:34-35
```
