### ISSUE TITLE
Shorter files name and Vietnamese Bible

### ISSUE THREAD

**Issue by dannuen** [GsLogiMaker/my-bible-obsidian-plugin#3]
Hi, I love the plugin. Just 1 thing I want to suggest is that, I have been using Joschua's system for a long time with the plugin Bible Linker. Basically this plugin let me call any verse or verses that I want and insert them into my note using the {book name}-{chapter},{verse} format (e.g: Genesis 1:1 will be gen-1,1). If you could make an option that build the Bible and name each chapter using the shorten name like gen, exo,... would be great, because I won't have to type out the whole name of the book everytime I want to link the verse.

Secondly, I'm using the Vietnamese Bible (BTT1925), can you help make this version available to build thru your plugin too?

Once again, great work. God Bless!

**Comment by GsLogiMaker** [comment]
I think I could add an abbreviation setting. As long as each names can be uniquely sliced down to three letters, it should work. However, I'm going out of town this week, and I might not be able to get to it till next week.

As for the Vietnamese Bible, I don't directly control the translation list, because I use an external API for the Bibles. However, you can find the contact information for the maintainer of the API here: https://bolls.life/api/
If he adds it to his API then it will also appear in the plugin.

Blessings!

**Comment by dannuen** [comment]
Additionally, I have another suggestion for improving the reading experience. Could you provide an option where the last chapters of each book link to the first chapter of the same book, rather than linking to the first chapter of the next book? This would enhance continuity and navigation for users.

**Comment by dannuen** [comment]
I contacted the maintainer of the Boll Bible API for the Vietnamese translation and he agreed.

**Comment by GsLogiMaker** [comment]
I've added the features you requested. You should now be able to build with abbreviated book names, and links to the first and last chapter of the current book.

To add links to the first and last chapters of the current book requires adding it to the `Chapter body format` setting. Here is a format you can use to add the links:
```

###### [[{first_chapter_name}|{book} 1 ⏮]] | [[{last_chapter_name}|{last_chapter_book} {last_chapter} ◀]] | [[{book}]] | [[{next_chapter_name}|▶ {next_chapter_book} {next_chapter}]] | [[{final_chapter_name}|⏭ {book} {final_chapter}|]]

{verses}

###### [[{first_chapter_name}|{book} 1 ⏮]] | [[{last_chapter_name}|{last_chapter_book} {last_chapter} ◀]] | [[{book}]] | [[{next_chapter_name}|▶ {next_chapter_book} {next_chapter}]] | [[{final_chapter_name}|⏭ {book} {final_chapter}|]]


```
