### ISSUE TITLE
Search does not work inside notes

### ISSUE THREAD

**Issue by aaanadie1** [GsLogiMaker/my-bible-obsidian-plugin#32]
I installed and enabled My Bible, 1.2.1 version, then downloaded translation "Spanish Español - RV2004 - Reina Valera Gómez 2004", then "Build Bible", so I can see a new vault named "My Bible" and can see "01 Génesis", "02 Éxodo", ... "66 Apocalipsis", so everything is working ok except search, if I search "Dios", "Sábado", or any other word got no results.
Search is working perfect for my other vaults, only fail for My Bible, but if I search for a title like Génesis, then search works ok, the problem is searching inside a note, for example, searching for "Dios" should get several results (Gen 1:1 En el principio creó Dios el cielo y la tierra.) but got nothing. Searching inside notes works without issues for the other vaults, does not work just for My Bible.
The problem is the same in Android and Linux Manjaro.

To reproduce this issue just install My Bible, download translation "Spanish Español - RV2004 - Reina Valera Gómez 2004" and make a note search like searching for Dios.

Thanks in advance.

**Comment by GsLogiMaker** [comment]
Did you build with dynamic verses enabled? Dynamic verses replaces the text of the verses with codeblocks that fetch the text when they are processed. This means the files don't actually contain the text you see. If you disable `Build with dynamic verses`, then the text of verses will be saved inside the files and allow for searching.

![mybible_example_disable_dynamic_verses](https://github.com/user-attachments/assets/07828591-50df-4ee4-9968-c25fa450ea23)

**Comment by aaanadie1** [comment]
Hello,
Yes, I build with "Build with dynamic verses" enabled, but I disabled it and rebuild My Bible and the search feature is working perfect. Thanks a lot for your fast answer.
