### ISSUE TITLE
Random verse function

### ISSUE THREAD

**Issue by isaacjoel** [GsLogiMaker/my-bible-obsidian-plugin#33]
I would like to be able to add a tag in my daily notes template so a different random verse appears in each of my daily notes.

**Comment by GsLogiMaker** [comment]
That could be doable.

**Comment by GsLogiMaker** [comment]
Here's how I plan for the syntax to be like:
```verse
random "<optional seed>"
```
And then you could write these in your daily notes using the date as the seed.
However, I believe most random verse generators pick from a preselected list of verses. I don't really have the time to curate a list like this so it'll have to be purely random, which might not give great results. What do you think?
