### ISSUE TITLE
Referencing a paragaph instead of one verse

### ISSUE THREAD

**Issue by limmh4988** [GsLogiMaker/my-bible-obsidian-plugin#39]
Quick question if it's possible to reference a few verses, say Genesis 1:1-3 instead of just verse 1? New to obsidian here. Might be an obsidian thing rather than an plug-in issue.

**Comment by GsLogiMaker** [comment]
There is a community plugin called Link Range that allows you to do that. You can find it by browsing the community plugins in Obsidian or going to this link: https://github.com/rmellmer/obsidian-link-range

**Comment by limmh4988** [comment]
Still couldnt get the plugin working. Only the chapter reference link work, but not the verses :(
