### ISSUE TITLE
MyBible update failed.

### ISSUE THREAD

**Issue by Mondonion** [GsLogiMaker/my-bible-obsidian-plugin#40]
I have 1.2.1 of MyBible and get the message "failed to update plugin MyBible" when trying to update to 1.3.0. This is the only time I've ever gotten this message when updating a plugin for Obsidian. In the meantime, everything works fine, and I am grateful for the MyBible plugin.  OS is Windows 11;  Obsidian 1.7.4

**Comment by GsLogiMaker** [comment]
I didn't realize Obsidian was serving version 1.3.0. I didn't mean to make it accessible yet, because I'm still working on it. Are you still able to use version 1.2.1?

**Comment by Mondonion** [comment]
Yes I still have version 1.2.1 and it’s working fine.  The update for the plug-in just won’t work.  So everything‘s working fine with 1.2.1 and I appreciate the work you’ve done on this.  The Bible is indispensable to me.  Sent from my iPhoneOn Oct 30, 2024, at 3:57 PM, GsLogiMaker ***@***.***> wrote:﻿
I didn't realize Obsidian was serving version 1.3.0. I didn't mean to make it accessible yet, because I'm still working on it. Are you still able to use version 1.2.1?

**Comment by Kabellosan** [comment]
Yep, can confirm 1.3 seems to have been sent out. What a spook. Manually installing 1.2.1 works like a charm, though. Thanks so much for this! Terrific! :D

**Comment by billpetro** [comment]
What am I doing wrong. I'm running the latest Obsidian 1.7.7 and the latest version 1.3.3 of My Bible, but I get this code in all my Bible book chapters, rather than the text I used to have:

![Revelation_1_-_Bill_Petro_-_Obsidian_v1_7_7](https://github.com/user-attachments/assets/5eb739df-3cd2-4b10-a08f-b7eeff134b92)

**Comment by GsLogiMaker** [comment]
@billpetro Can you try building your Bible again?
