### ISSUE TITLE
 Request to Add Chinese Union Version (Simplified) to Translation Options

### ISSUE THREAD

**Issue by gpgao** [GsLogiMaker/my-bible-obsidian-plugin#5]
I hope this message finds you well. I'm a user of the "My Bible" plugin for Obsidian, and it has been a tremendous tool in my daily studies. I've been enjoying the ability to integrate my Bible study into my Obsidian vault. However, I noticed that while there are various translations available, the Chinese Union Version in Simplified Chinese (和合本中文简体版) is not currently an option.

The Chinese Union Version is widely used among Chinese-speaking Christians and is highly regarded for its accuracy and readability. Having this version available would be beneficial for native Chinese speakers and those studying the language and the Bible concurrently.

Would it be possible to include the Chinese Union Version (Simplified) in the list of available translations? This addition would surely enhance the plugin's usefulness and accessibility for a broader audience.

Thank you for considering my request. I appreciate the work you've put into creating and maintaining this plugin.

**Comment by GsLogiMaker** [comment]
Blessings!
My Bible uses independent sites to download translations, so I don't directly control which translations are available. However you can speak with the maintainer of the BollsLife API (which is where My Bible gets its translations from) and ask him to add it. If he adds the translations there then it will appear in My Bible as well.
You can find his contact information here: https://bolls.life/api/#contact_me
Hope this helps!
