### ISSUE TITLE
HTML Tag Visible in NIV Bible Text

### ISSUE THREAD

**Issue by gpgao** [GsLogiMaker/my-bible-obsidian-plugin#6]
Dear GsLogiMaker,

I hope this message finds you well. I've noticed an issue in the NIV version of the Bible text generated by your application where an HTML break line tag (<br/>) is appearing within the scripture text. This tag seems to be present only in the NIV version and is not found in other versions.

Additionally, I'd like to mention that my settings have "build with dynamic verses" turned off.

I'm looking forward to your response and hope for a solution that will improve the readability of the scriptures in the NIV version.

Best regards,
gpgao
![屏幕截图 2024-04-01 170330](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/45122325/50142893-7fd8-4855-b7c3-df30fc4fe54f)

**Comment by GsLogiMaker** [comment]
I'll see about getting that fixed. Thanks for letting me know!

**Comment by GsLogiMaker** [comment]
I've released an update fixing this instance. I'll keep this issue open for a while in case there are other tags not displaying properly.

**Comment by gpgao** [comment]
Dear GsLogiMaker,

Thank you for your attention. 
I have reviewed the Isaiah 53 passage in the CUNPS (Chinese Union New Punctuation Simplified) version and found the <br> tag present. This is likely an oversight in the HTML markup which should not be visible in the text.

Warm regards,

gpgao

![image](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/45122325/41cc8739-2aea-43be-9557-c4e73f02ef00)
![image](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/45122325/0e4b048d-0665-4d60-a20e-26ff30819c5f)

**Comment by GsLogiMaker** [comment]
I'm using the latest version of MyBible and I don't see it. I believe you have to update MyBible manually, and if you do that it should bed fixed.

If you go to the community plugins tab in the settings then click on MyBible, it will take you to the download page where there should be a button to update the plugin.

**Comment by gpgao** [comment]
Dear GsLogiMaker,

Thank you very much for your prompt attention and efforts to address the issue I've reported. I truly appreciate it.

I have followed your guidance and checked the versions of both the "My Bible" plugin and Obsidian. Currently, I am using version 1.1.4 of the "My Bible" plugin and version v1.5.12 of Obsidian.

Despite updating and ensuring everything is current, I am still encountering the issue with the <br> tag appearing within the text of Isaiah 53 in the CUNPS version. For clarity and reference, I have attached the settings of the plugin as they are configured on my system.


I wonder if there might be an additional step or configuration I am missing that could resolve this issue. Any further guidance or suggestions you could provide would be greatly appreciated.

Thank you once again for your support and the effort you put into maintaining and improving this plugin. It plays a significant role in my study and engagement with the scriptures.

Warm regards,


![image](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/45122325/16386109-f264-4a62-9fda-deb9e18a5799)
![image](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/45122325/41e7d242-7b03-4601-a63f-81c38e169687)

**Comment by hopperbk** [comment]
I agree with @gpgao - in version 1.1.4 the same issue was fixed with the NIV version.  Unfortunately, it still manifests in the Message (MSG) when downloading.  I have the same settings as gpgao.

**Comment by hopperbk** [comment]
In addition, the default settings create links for the first chapter of each book, the previous chapter, the current book, the next chapter, and the last chapter of each book.  All works perfectly except for the link to the book itself (ie: "Genesis").  Nothing in the parsing of the text creates a file for the book as a whole.  Is it possible to enhance the logic to create a single file for each book that contains links to all the chapters (and optionally verses) for that book, so that the default link goes to a valid page, versus a non-existent link?

![MissingBookFile](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/1882287/94dc44ac-af11-4bb1-8135-dad38881cfbf)

Awesome plugin by the way!  Saved me tons of time importing multiple translations into my vault!

**Comment by GsLogiMaker** [comment]
Yeah I could definitely add a generator for book header files. Don't know why I didn't think of that sooner. 😅

**Comment by GsLogiMaker** [comment]
> I agree with @gpgao - in version 1.1.4 the issue was fixed with the NIV version. Unfortunately, it still manifests in The Message (MSG) when downloading.

Could you give a specific chapter/verse where this occurs?

**Comment by GsLogiMaker** [comment]
> Yeah I could definitely add a generator for book header files. Don't know why I didn't think of that sooner. 😅

I created an issue to track this feature #12 . Any further discussion of the topic should be done there. 👍

**Comment by hopperbk** [comment]
> Could you give a specific chapter/verse where this occurs?

Unfortunately, I've already done the global fix with a text editor, and I'd rather not screw up my synching by re-importing the MSG, but if memory services, Genesis 1:3 was a verse that I saw the <br/> tags in, if that helps.
