### ISSUE TITLE
Support my ideal Greek Bible setup

### ISSUE THREAD

**Issue by brederic** [GsLogiMaker/my-bible-obsidian-plugin#8]
This is what I would like to do:
Have a folder named "LXXGNT", for a complete Greek bible with LXX in the Old Testament and one of the the Greek New Testaments,  
I would like to use Young's Literal translation to build the book structure so I can use normal English names to link to these notes, and have English links between chapters and books.  
Then I would like to have the ability to rebuild the verse code in the Old Testament portions with something like "verse LXX 1  1  1  1" so that it will pull all the verses in the OT from LXX  and rebuild all the verse code in the New Testament portions with something like "verse GNT" so that it will pull all the verses in the NT from the GNT.

I know there are parts of the OT in the LXX where the chapters and verses do not perfectly align with our English Bibles, but this would get me 98% of the way there.

What do you think?

**Comment by GsLogiMaker** [comment]
I believe what you're asking should be do-able.

Normally, verses will display the translation you have currently selected in the settings, but you can force them to display a specific version be adding the abbreviated translation name to the end:
![image](https://github.com/GsLogiMaker/my-bible-obsidian-plugin/assets/87501052/da8ced28-9179-429e-b962-f60c7413710c)
You can build the whole Bible like this by adding it to the `Verse body format` setting.

You could then rebuild the Bible with Young's Literal Translation selected and you would have the English names for the books with the LXX text. (If you need a different translations for old and new testament, you may need to build the Bible twice and do some manual file manipulation to merge them.)

Let me know if this gets you there!

**Comment by brederic** [comment]
Wow, that's great.  It looks like you already support what I want to do.  I'll work on putting this in action and let you know if I have any trouble.

**Comment by brederic** [comment]
What would the verse body text setting look like for the example you gave?  I've tried a couple of things, but it is not putting LXX in the right place

**Comment by brederic** [comment]
I was able to get everything the way I would like by doing some regex find and replace in Notepad++ to add the version I wanted to all the verse links.  I now have my ideal Greek Bible setup. And I used the same technique to get my multiple English Bible setup way I wanted as as well.  Thanks for all you hard work on this amazing tool!

**Comment by GsLogiMaker** [comment]
Cool! Glad my over-engineering ended up being useful! 😅
